name: CI-CD
on:
  push:
    branches: [main]
    paths: ["src/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: { tag: ${{ steps.sha.outputs.tag }}
    steps:
      - id: sha
        run: echo "tag=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: techitfactory/python-app:${{ steps.sha.outputs.tag }}

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      TAG: ${{ needs.build.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          command -v yq >/dev/null || { wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod +x /usr/local/bin/yq; }
          yq eval -i '.image.tag = env(TAG)' charts/python-app/values.yaml
      - uses: EndBug/add-and-commit@v9
        with: { message: "Update image tag -> ${{ env.TAG }}" }
      - run: kubectl -n argo-cd apply -f charts/python-app   # plain sync; ARC pod has kube-config
